### PR TITLE
Add DocumentFragment alternative return

### LINKED ISSUE #2: Get DOM nodes back instead of HTML
Passing raw text and getting HTML can cause XSS: https://github.com/sindresorhus/refined-github/issues/510

`linkify-urls` could return a `DocumentFragment` like:

```
"textNode", Node(a[href=link](link)), "textNode"
```

### PR DESCRIPTION
**Pull request by fregante**
~~Has minor implementation diff error in the test. I'm not sure of how to test the DocumentFragment.~~

Fixes #2

### CODE REVIEW

**Comment by bfred-it** [comment]
😿 

screen shot 2017-06-23 at 15 13 13

**Comment by fregante** [comment]
😰 

screen shot 2017-06-23 at 15 13 13

**Comment by fregante** [comment]
I found a solution!

**Comment by fregante** [comment]
What do you prefer? Separate `linkifyUrls.getDom` method or is an option ok?

**Comment by sindresorhus** [comment]
Looks good. Option is ok. Could you document it?

**Comment by sindresorhus** [comment]
🙌

**Pull request merged**
