### PR TITLE
Add support for custom HTML value

### LINKED ISSUE #10: Allow custom HTML value
This would help solve sindresorhus/refined-github#703

```js
const linkify = (href, options) => createHtmlElement({
	name: 'a',
	attributes: Object.assign({href: ''}, options.attributes, {href}),
	value: options.value || href
}); 
```

If the user can pass the value as part of the options, the library can parse the href text and add an anchor element that has whatever the user wants as its text (HTML in the case of sindresorhus/refined-github#695 to preserve the span tags)

### PR DESCRIPTION
**Pull request by yeskunall**
Fixes #10

### CODE REVIEW

**Comment by fregante** [comment]
This fails with `value: <falsy value like 0 or ''>`

I'd suggest either `Object.assign` or a test against `undefined` instead of `||`

**Comment by yeskunall** [comment]
You are correct. It picks up `href` if the other value in the expression is falsy. Sorry, I'll look into it. 🙈

**Comment by fregante** [comment]
So close to a merge! :)

**Comment by yeskunall** [comment]
@bfred-it honestly was expecting it to be an easy fix, but I seem to be stumped. I could use some help here.

I started by simply wrapping `options.value` in a `String` so as to explicitly convert the `value`, since the end result is a string anyway, but that didn't work out.

> I'd suggest either Object.assign or a test against undefined instead of ||

Maybe you could elaborate a bit more on this?

**Comment by fregante** [comment]
`typeof options.value === ‘undefined’ ? href : options.value`

**Comment by fregante** [comment]
Thanks for the PR @yeskunall 🎉

**Pull request merged**
