### PR TITLE
Fix `*` and `$` not being linkified

### LINKED ISSUE #33: Asterisks in the hash aren't linkified correctly
```
https://crontab.guru/#1_*_*_*_*
```
```html
<a href=\"https://crontab.guru/#1_\">https://crontab.guru/#1_</a>*_*_*_*
```

Run this on [runkit](https://npm.runkit.com/linkify-urls): 

```js
require("linkify-urls")('https://crontab.guru/#1_*_*_*_*')
```

### PR DESCRIPTION
**Pull request by rocktimsaikia**
fixes #33 
Fixes the issue of asterisks not being linkified properly.
Added test for it too.

//@sindresorhus

### CODE REVIEW

**Comment by sindresorhus** [comment]
`*` is reserved and should have been percentage encoded: https://en.wikipedia.org/wiki/Percent-encoding#:~:text=Reserved%20characters%20are%20those%20characters,characters%20have%20no%20such%20meanings.

**Comment by rocktimsaikia** [comment]
@sindresorhus Ah I see. So doesn't that mean all the reserved characters should be percentage-encoded? Cause currently, none of the reserved characters are getting url-encoded.

**Comment by sindresorhus** [comment]
Hmm, seems to be conflicting info about this. The RFC actually allows unencoded `*`: https://stackoverflow.com/a/6533595/64949

**Comment by sindresorhus** [comment]
Can you make sure all the mentioned characters here are supported unencoded?

> Thus, only alphanumerics, the special characters `$-_.+!*'(),` and reserved characters used for their reserved purposes may be used unencoded within a URL.

**Comment by rocktimsaikia** [comment]
@sindresorhus Yes those characters are supported unencoded as stated on RFC. But still It does seem to have some conflicting views on this. May be cause most of us are not actually informed about this. So I guess we can just leave it as unencoded and mention about this information on the `Readme` properly so that others can know about it too.

**Comment by sindresorhus** [comment]
> So I guess we can just leave it as unencoded and mention about this information on the Readme properly so that others can know about it too.

I'm not sure what you're saying here, but I'm saying I'm ok with this PR if you ensure all the mentioned characters are supported.

**Comment by rocktimsaikia** [comment]
@sindresorhus  Ah sorry I misunderstood it. I checked and the dollar sign `$` was not supported too. I added it as well along with a test for it too.

**Pull request merged**
